Update secret_scanning.yml

diff --git a/.github/workflows/secret_scanning.yml b/.github/workflows/secret_scanning.yml
--- a/.github/workflows/secret_scanning.yml
+++ b/.github/workflows/secret_scanning.yml
@@ -1,8 +1,4 @@
 name: 'detect-secrets Action'
-#description: 'Scans your GitHub repository for accidentally committed secrets, enhances code security, and aids in secret cleanup.'
-#branding:
-#  icon: 'alert-octagon'
-#  color: 'red'
   
 on:
   push:
@@ -19,9 +15,16 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Install pip detect-secrets
+      - name: Install necessary packages
         run: |
-          pip install detect-secrets
+          # This is the experimental version of slim-detect-secrets.
+          # It will be updated to the official Yelp/detect-secrets version once the customized plugins are merged.
+          # For more information about slim/detect-secrets, check the following:
+          # 1. https://github.com/NASA-AMMOS/slim-detect-secrets/tree/exp
+          # 2. https://github.com/NASA-AMMOS/slim/blob/d20ee6134a0dc0e0dab11d2d2570e358ef7e4550/continuous-testing/starter-kits/README.md#detect-secrets
+          pip install git+https://github.com/NASA-AMMOS/slim-detect-secrets.git@exp
+          # This library is used for JSON operations.
+          pip install jq
           
       - name: Create an initial .secrets.baseline if .secrets.baseline does not exist
         run: |
@@ -38,28 +41,37 @@ jobs:
           fi
 
       - name: Scan repository for secrets
-        id: save_output
         run: |
           # scripts to scan repository for new secrets
           
           # backup the list of known secrets
           cp .secrets.baseline .secrets.new
-          
-          echo $(cat .secrets.new)
 
           # find the secrets in the repository
-          #detect-secrets scan --baseline .secrets.new --exclude-files '.git*' > secrets-result.txt
-          detect-secrets scan --baseline .secrets.new --no-verify --all-files > secrets-result.txt
-          echo $(cat secrets-result.txt)
-          
-          # export the result of the scan as an artifact
-          echo "✅ Scan completed. Exporting the result as an artifact."
-          echo "The output is ${{ steps.save_output.outputs.files }}"
+          detect-secrets scan --baseline .secrets.new --exclude-files '.secrets.*' --exclude-files '.git*'
+               
+          # if there is any difference between the known and newly detected secrets, break the build
+          # Function to compare secrets without listing them
+          compare_secrets() { diff <(jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$1" | sort) <(jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$2" | sort) >/dev/null; }
+        
+          # Check if there's any difference between the known and newly detected secrets
+          if ! compare_secrets .secrets.baseline .secrets.new; then
+            echo "⚠️ Attention Required! ⚠️" >&2
+            echo "New secrets have been detected in your recent commit. Due to security concerns, we cannot display detailed information here and we cannot proceed until this issue is resolved." >&2
+            echo "" >&2
+            echo "Please follow the steps below on your local machine to reveal and handle the secrets:" >&2
+            echo "" >&2
+            echo "1️⃣ Run the 'detect-secrets' tool on your local machine. This tool will identify and clean up the secrets. You can find detailed instructions at this link: https://nasa-ammos.github.io/slim/continuous-testing/starter-kits/#detect-secrets" >&2
+            echo "" >&2
+            echo "2️⃣ After cleaning up the secrets, commit your changes and re-push your update to the repository." >&2
+            echo "" >&2
+            echo "Your efforts to maintain the security of our codebase are greatly appreciated!" >&2
+            exit 1
+          fi
 
-      - name: Upload artifact
+      - name: Upload secret detection results
+        if: ${{ steps.scan-secrets.outcome == 'failure' }}
         uses: actions/upload-artifact@v2
         with:
-          name: target
-          path: ${{github.workspace}}/target
-
-          
+          name: secret-detection-results
+          path: .secrets.new
